-- Fase 1: segurança de autenticação. Compatível com o sistema .NET legado (só adiciona).

-- Hash de senha (Argon2id/bcrypt). A coluna SENHA (texto) é mantida enquanto o
-- legado estiver no ar; após a virada, ver 900_remover_senha_texto.sql.
ALTER TABLE USUARIO ADD COLUMN SENHA_HASH VARCHAR(255) NULL AFTER SENHA;

CREATE TABLE IF NOT EXISTS REFRESH_TOKEN (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID  BIGINT       NOT NULL,
    TOKEN_HASH  CHAR(64)     NOT NULL,
    EXPIRA_EM   DATETIME     NOT NULL,
    REVOGADO_EM DATETIME     NULL,
    USER_AGENT  VARCHAR(255) NULL,
    IP          VARCHAR(45)  NULL,
    CRIADO_EM   DATETIME     NOT NULL,
    UNIQUE KEY UX_REFRESH_TOKEN_HASH (TOKEN_HASH),
    KEY IX_REFRESH_TOKEN_USUARIO (USUARIO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PASSWORD_RESET (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID  BIGINT   NOT NULL,
    TOKEN_HASH  CHAR(64) NOT NULL,
    EXPIRA_EM   DATETIME NOT NULL,
    USADO_EM    DATETIME NULL,
    CRIADO_EM   DATETIME NOT NULL,
    UNIQUE KEY UX_PASSWORD_RESET_HASH (TOKEN_HASH),
    KEY IX_PASSWORD_RESET_USUARIO (USUARIO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AUDITORIA (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    INSTITUICAO_ID BIGINT       NOT NULL,
    USUARIO_ID     BIGINT       NULL,
    ACAO           VARCHAR(60)  NOT NULL,
    ENTIDADE       VARCHAR(60)  NOT NULL,
    ENTIDADE_ID    BIGINT       NULL,
    DADOS          JSON         NULL,
    IP             VARCHAR(45)  NULL,
    CRIADO_EM      DATETIME     NOT NULL,
    KEY IX_AUDITORIA_ENTIDADE (ENTIDADE, ENTIDADE_ID),
    KEY IX_AUDITORIA_INSTITUICAO (INSTITUICAO_ID, CRIADO_EM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Login busca por e-mail
CREATE INDEX IX_USUARIO_EMAIL ON USUARIO (EMAIL);
