-- Fase 3: comunidade. Só adiciona colunas/índices (compatível com o legado).

-- Anotações de vídeo passam a ter dono. No legado não havia USUARIO_ID, então as
-- anotações de um aluno apareciam para todos. As antigas (USUARIO_ID nulo) ficam
-- visíveis só para a equipe.
ALTER TABLE VIDEO_ANOTACAO ADD COLUMN USUARIO_ID BIGINT NULL AFTER DISCIPLINA_ID;
CREATE INDEX IX_VIDEO_ANOTACAO_USUARIO ON VIDEO_ANOTACAO (USUARIO_ID, DISCIPLINA_ID);

-- Chat: marca de leitura para o contador de não lidas (USUARIO.MSG_NO_VIEW)
ALTER TABLE CHAT_MENSAGENS ADD COLUMN LIDA_EM DATETIME NULL;
CREATE INDEX IX_CHAT_CONVERSA ON CHAT_MENSAGENS (INSTITUICAO_ID, USUARIO_SEND_ID, USUARIO_RECEIVE_ID, ID);
CREATE INDEX IX_CHAT_NAO_LIDAS ON CHAT_MENSAGENS (USUARIO_RECEIVE_ID, LIDA_EM);

CREATE INDEX IX_FORUM_DISCIPLINA ON FORUM (INSTITUICAO_ID, LISTA_DISCIPLINA_ID);
CREATE INDEX IX_FORUM_DISCURSAO_FORUM ON FORUM_DISCURSAO (FORUM_ID);
