-- Fase 4: secretaria. Só índices (compatível com o legado).
CREATE INDEX IX_USUARIO_INST_CPF ON USUARIO (INSTITUICAO_ID, CPF);
CREATE INDEX IX_INSCRICAO_USUARIO ON INSCRICAO (INSTITUICAO_ID, USUARIO_ID);
CREATE INDEX IX_USUARIO_CURSO_INSCRICAO ON USUARIO_CURSO (INSCRICAO_ID);
