-- Fase 5: financeiro. Só adiciona (compatível com o legado).

-- Eventos de pagamento (webhooks e sincronizações): idempotência + trilha de auditoria.
CREATE TABLE IF NOT EXISTS PAGAMENTO_EVENTO (
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    INSTITUICAO_ID   BIGINT       NOT NULL,
    GATEWAY          VARCHAR(30)  NOT NULL,
    EVENTO_ID        VARCHAR(120) NOT NULL,
    CONTA_RECEBER_ID BIGINT       NULL,
    STATUS           VARCHAR(30)  NOT NULL,
    PAYLOAD          JSON         NULL,
    CRIADO_EM        DATETIME     NOT NULL,
    UNIQUE KEY UX_PAGAMENTO_EVENTO (GATEWAY, EVENTO_ID, STATUS),
    KEY IX_PAGAMENTO_EVENTO_CR (CONTA_RECEBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IX_CR_INST_USUARIO_VENC ON CONTAS_RECEBER (INSTITUICAO_ID, USUARIO_ID, DATA_VENCIMENTO);
CREATE INDEX IX_CR_INST_SITUACAO ON CONTAS_RECEBER (INSTITUICAO_ID, LISTA_SITUACAO_CR_ID);
CREATE INDEX IX_CP_INST_VENC ON CONTAS_PAGAR (INSTITUICAO_ID, DATA_VENCIMENTO);
